name: Normal Issue Form
description: フォームサンプル
title: "[BUG] <title>"
labels: ["Bug", "Needs Triage"]
body:
- type: textarea
  attributes:
    label: 概要
    description: 概要
  validations:
    required: false
- type: textarea
  attributes:
    label: 詳細
    description: 詳細
  validations:
    required: false
- type: textarea
  attributes:
    label: 親タスク
    description: 親タスク
  validations:
    required: false
- type: textarea
  attributes:
    label: アクションリスト
    description: アクションリスト
  validations:
    required: false
- type: textarea
  attributes:
    label: 関連資料
    description: 関連資料
  validations:
    required: false
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Steps to reproduce the behavior.
    placeholder: |
      1. In this environment...
      1. With this config...
      1. Run '...'
      1. See error...
  validations:
    required: false
- type: textarea
  attributes:
    label: Environment
    description: |
      examples:
        - **OS**: Ubuntu 20.04
        - **Node**: 13.14.0
        - **npm**: 7.6.3
    value: |
        - OS:
        - Node:
        - npm:
    render: markdown
  validations:
    required: false
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? References? Anything that will give us more context about the issue you are encountering!

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
